import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.useQueries((t) => {
    return ["A", "B", "C"].map((x) =>
      t.example.hello(
        { text: x },
        {
          enabled: false,
          onSuccess: () => {
            // I can write whatever I want here, it will never execute!
            console.log("QUERY", x, "COMPLETED (not really)");
          },
        }
      )
    );
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-4 bg-slate-900 text-center text-white">
        <h1 className="text-2xl">Showing tRPC bug</h1>
        <div className="flex gap-8">
          {hello.map((q, i) => (
            <div key={i} className="rounded bg-slate-700 px-4 py-2">
              {JSON.stringify(q.data)}
            </div>
          ))}
        </div>
        <p>
          <b>Explanation:</b> Notice that all queries have{" "}
          <span className="inline-block bg-slate-800">
            {"{ enabled: false }"}
          </span>{" "}
          added to them, yet they are still being loaded.
        </p>

        <a
          className="text-emerald-400 hover:underline"
          href="https://github.com/HatulaPro/showing-usequeries-bug"
        >
          Github
        </a>
      </main>
    </>
  );
};

export default Home;
